"""empty message

Revision ID: 6fb5aee48d63
Revises: bebfcd0fad26
Create Date: 2017-06-11 11:25:06.874730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fb5aee48d63'
down_revision = 'bebfcd0fad26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disciplinas', sa.Column('in_obrigatorio', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disciplinas', 'in_obrigatorio')
    # ### end Alembic commands ###
