"""Inicializacao

Revision ID: bebfcd0fad26
Revises: 
Create Date: 2017-06-10 21:43:46.065093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bebfcd0fad26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coordenacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.UnicodeText(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('fluxos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descricao')
    )
    op.create_table('perfis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('salas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=64), nullable=True),
    sa.Column('localizacao', sa.String(length=64), nullable=True),
    sa.Column('campus', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descricao')
    )
    op.create_table('status_solcitacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descricao')
    )
    op.create_table('disciplinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=True),
    sa.Column('periodo', sa.Integer(), nullable=True),
    sa.Column('carga_horaria', sa.Integer(), nullable=True),
    sa.Column('fluxo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fluxo_id'], ['fluxos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('lotacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coordenacao_id', sa.Integer(), nullable=True),
    sa.Column('semestre', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['coordenacao_id'], ['coordenacoes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('semestre')
    )
    op.create_table('transacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=True),
    sa.Column('perfil_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfis.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('nome', sa.String(length=64), nullable=True),
    sa.Column('coordenacao_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('in_coordenador', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['coordenacao_id'], ['coordenacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_nome'), 'usuarios', ['nome'], unique=False)
    op.create_table('itens_lotacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turma', sa.String(length=2), nullable=True),
    sa.Column('in_solitacao', sa.String(length=1), nullable=True),
    sa.Column('status_solcitacao_id', sa.Integer(), nullable=True),
    sa.Column('lotacao_id', sa.Integer(), nullable=True),
    sa.Column('diciplina_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['diciplina_id'], ['disciplinas.id'], ),
    sa.ForeignKeyConstraint(['lotacao_id'], ['lotacoes.id'], ),
    sa.ForeignKeyConstraint(['status_solcitacao_id'], ['status_solcitacoes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('turma')
    )
    op.create_table('perfis_usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('perfil_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfis.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dia', sa.String(length=10), nullable=True),
    sa.Column('item_lotacao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_lotacao_id'], ['itens_lotacao.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dia')
    )
    op.create_table('horarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horario', sa.String(length=1), nullable=True),
    sa.Column('item_lotacao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_lotacao_id'], ['itens_lotacao.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('horario')
    )
    op.create_table('salas_itens_lotacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sala_id', sa.Integer(), nullable=True),
    sa.Column('item_lotacao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_lotacao_id'], ['itens_lotacao.id'], ),
    sa.ForeignKeyConstraint(['sala_id'], ['salas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios_itens_lotacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.Column('item_lotacao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_lotacao_id'], ['itens_lotacao.id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios_itens_lotacao')
    op.drop_table('salas_itens_lotacao')
    op.drop_table('horarios')
    op.drop_table('dias')
    op.drop_table('perfis_usuarios')
    op.drop_table('itens_lotacao')
    op.drop_index(op.f('ix_usuarios_nome'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('transacoes')
    op.drop_table('lotacoes')
    op.drop_table('disciplinas')
    op.drop_table('status_solcitacoes')
    op.drop_table('salas')
    op.drop_table('perfis')
    op.drop_table('fluxos')
    op.drop_table('coordenacoes')
    # ### end Alembic commands ###
