"""empty message

Revision ID: d08a39e3ab63
Revises: 6fb5aee48d63
Create Date: 2017-06-11 14:47:04.836272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd08a39e3ab63'
down_revision = '6fb5aee48d63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transacoes_por_perfil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('perfil_id', sa.Integer(), nullable=True),
    sa.Column('transacao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfis.id'], ),
    sa.ForeignKeyConstraint(['transacao_id'], ['transacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(None, 'transacoes', type_='foreignkey')
    op.drop_column(u'transacoes', 'perfil_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'transacoes', sa.Column('perfil_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'transacoes', 'perfis', ['perfil_id'], ['id'])
    op.drop_table('transacoes_por_perfil')
    # ### end Alembic commands ###
